title: Mi sitio Jekyll
author: Tu Nombre
description: Sitio web de ejemplo

collections:
  proyectos:
    output: true

nav:
  - title: Inicio
    url: /
  - title: Acerca de
    url: /about.html
  - title: Contacto
    url: /contact.html
  - title: Proyectos
    url: /proyectos.html

